controller_list:
  - name: fake_arm_planning_group_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_grip_planning_group_controller
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses.
  - group: arm_planning_group
    pose: frontup
  - group: grip_planning_group
    pose: close1